// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7UeHZvmwaOK4xFG_k2Val8spJ4p5luI',
    appId: '1:1067712099961:web:13eab44bb4f28e82de86a8',
    messagingSenderId: '1067712099961',
    projectId: 'know-your-flow-26e8d',
    authDomain: 'know-your-flow-26e8d.firebaseapp.com',
    storageBucket: 'know-your-flow-26e8d.firebasestorage.app',
    measurementId: 'G-HGDYN13M82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSgfueAnLN-F2yKTUxcqEoVmlWKDFqjSA',
    appId: '1:1067712099961:android:5aeff2e16d2bbbe6de86a8',
    messagingSenderId: '1067712099961',
    projectId: 'know-your-flow-26e8d',
    storageBucket: 'know-your-flow-26e8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBz_KE2wBe822gZOLlt4qRtcNtUfjgDg',
    appId: '1:1067712099961:ios:ccb891922c32cd89de86a8',
    messagingSenderId: '1067712099961',
    projectId: 'know-your-flow-26e8d',
    storageBucket: 'know-your-flow-26e8d.firebasestorage.app',
    iosBundleId: 'com.example.knowYourFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBz_KE2wBe822gZOLlt4qRtcNtUfjgDg',
    appId: '1:1067712099961:ios:ccb891922c32cd89de86a8',
    messagingSenderId: '1067712099961',
    projectId: 'know-your-flow-26e8d',
    storageBucket: 'know-your-flow-26e8d.firebasestorage.app',
    iosBundleId: 'com.example.knowYourFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7UeHZvmwaOK4xFG_k2Val8spJ4p5luI',
    appId: '1:1067712099961:web:2b7c0e4e61aa4073de86a8',
    messagingSenderId: '1067712099961',
    projectId: 'know-your-flow-26e8d',
    authDomain: 'know-your-flow-26e8d.firebaseapp.com',
    storageBucket: 'know-your-flow-26e8d.firebasestorage.app',
    measurementId: 'G-CJ3JZSNZLZ',
  );
}
