import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'package:device_preview/device_preview.dart';

// Screens
import 'theme.dart';
import 'screens/home_public_screen.dart';
import 'screens/home_logged_screen.dart';
import 'screens/tracker_screen.dart';
import 'screens/education_screen.dart';
import 'screens/auth_screen.dart';
import 'screens/profile_setup_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    DevicePreview(
      enabled: true, // Turn off for production
      builder: (context) => const KnowYourFlowApp(),
    ),
  );
}

class KnowYourFlowApp extends StatelessWidget {
  const KnowYourFlowApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Know Your Flow',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      useInheritedMediaQuery: true, // ✅ For DevicePreview
      locale: DevicePreview.locale(context),
      builder: DevicePreview.appBuilder,

      // ✅ Define app navigation flow
      initialRoute: '/publicHome',
      routes: {
        '/publicHome': (context) => const HomeScreen(), // old welcome home
        '/auth': (context) => const AuthScreen(),
        '/profileSetup': (context) => const ProfileSetupScreen(),
        '/home': (context) => const HomeLoggedScreen(), // new logged-in dashboard
        '/tracker': (context) => const TrackerScreen(),
        '/education': (context) => const EducationScreen(),
      },
    );
  }
}

// Optional bottom navigation (used only for logged-in screens)
class MainNavigation extends StatefulWidget {
  const MainNavigation({super.key});

  @override
  State<MainNavigation> createState() => _MainNavigationState();
}

class _MainNavigationState extends State<MainNavigation> {
  int _selectedIndex = 0;

  final List<Widget> _screens = const [
    HomeLoggedScreen(), // logged-in home
    TrackerScreen(),
    EducationScreen(),
    AuthScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _screens[_selectedIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _selectedIndex,
        onTap: (i) => setState(() => _selectedIndex = i),
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.calendar_today), label: 'Tracker'),
          BottomNavigationBarItem(icon: Icon(Icons.school), label: 'Education'),
          BottomNavigationBarItem(icon: Icon(Icons.person), label: 'Account'),
        ],
      ),
    );
  }
}
